### ISSUE TITLE
setup wizard

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#59]
I'll be creating separate issues for each screen.

## Screens
- [x] welcome splash https://github.com/wpCloud/wp-stateless/issues/60
- [x] step one - google login https://github.com/wpCloud/wp-stateless/issues/61
- [x] step two - setup project https://github.com/wpCloud/wp-stateless/issues/62
- [ ] step three - complete https://github.com/wpCloud/wp-stateless/issues/63

**Comment by ewsopp** [comment]
- [x] @alimuzzaman remove the `Free & Paid Plans` section from the welcome screen of the Setup Assistant. 

![image](https://user-images.githubusercontent.com/5578537/28080004-727a032e-6638-11e7-8a8c-c5f58d419745.png)
