### ISSUE TITLE
setup wizard - setup project

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#62]
# Cases
- [x] User has no project and no billing account. https://github.com/wpCloud/wp-stateless/issues/62#issuecomment-272938674
- [x] User has project(s), but no billing account. https://github.com/wpCloud/wp-stateless/issues/62#issuecomment-272941067
- [x] User has project(s) and billing account(s). https://github.com/wpCloud/wp-stateless/issues/62#issuecomment-272945625

**Comment by ewsopp** [comment]
## User has no project.

![image](https://cloud.githubusercontent.com/assets/5578537/21995366/8940df40-dbf2-11e6-8811-3f7b6740dd37.png)

If the user has no Google Cloud projects and no billing account, then we send them to the below screen.

inspect this design at https://projects.invisionapp.com/d/main#/console/10029877/214382608/inspect

- [x] Show the user's google account avatar, name, and email address.
- [x] The "Logout" button allows them to logout of the current Google account. If they click this, log them out of the account, and send them back to Step 1 (login with google).

![image](https://cloud.githubusercontent.com/assets/5578537/21995380/a65d00fe-dbf2-11e6-8ed7-54d7162ba27a.png)

- [x] "Set Google Billing" button should open a new tab to https://console.cloud.google.com/billing
- [x] Poll the Google Billing API checking to see if they have created the Billing Account.
- ~~Whiling polling, add "Checking..." text to the right of the "Set Google Billing" button and animate the ...~~

![image](https://cloud.githubusercontent.com/assets/5578537/21995509/5165c120-dbf3-11e6-99e3-4f5712f7a154.png)

- [x] Once a billing account is detected, send the user to the next screen...

![image](https://cloud.githubusercontent.com/assets/5578537/21995575/a8b66948-dbf3-11e6-83d6-8f75064e4852.png)

**Comment by ewsopp** [comment]
#  User has project(s), but no billing account.

![image](https://cloud.githubusercontent.com/assets/5578537/21995697/3677116a-dbf4-11e6-9112-907ded1c354e.png)

If the user has a Google Cloud project, but has no billing account - we present this screen.

inspect this design at https://projects.invisionapp.com/d/main#/console/10029877/214381034/inspect

## Google Cloud Project

![image](https://cloud.githubusercontent.com/assets/5578537/21995743/8536203e-dbf4-11e6-96b7-6a5fe7459cd7.png)

- [x] the first option "Google Cloud Project" sets the google cloud project used by WP-Stateless.
- [x] this field is a text field and drop down.
- [x] the default option is the website's domain name. convert periods to dashes. ex: `usabilitydynamics.com` would be `usability-dynamics-com`.
- [x] if the user clicks into the field, they can edit the text value or select one of the other options under existing projects.
- [x] if the user customizes the new project name, show it change in real time in the drop down option.
- [x] if the user selects an existing project, put that project's name in the field and allow the user to select the 'create new project' option again.

## Google Cloud Bucket

![image](https://cloud.githubusercontent.com/assets/5578537/21995963/dbf141fa-dbf5-11e6-8cca-daebd08cba0d.png)

- [x] this field should function very similar to the previous "Google Cloud Project" option.
- [x] the default option should their website address with `stateless-` prefixed. example: `usabilitydynamics.com` would be `stateless-usability-dynamics-com`.
- [x] if user changes the previous Google Cloud Project option, check to see if there are buckets to list. Buckets are tied to Projects, so you need to recheck each time the project is changed.

## Google Cloud Billing

![image](https://cloud.githubusercontent.com/assets/5578537/21996125/b120d37c-dbf6-11e6-9173-24c90b9c99df.png)

- [x] "Set Google Billing" button should open a new tab to https://console.cloud.google.com/billing
- [x] Poll the Google Billing API checking to see if they have created the Billing Account.
- ~~Whiling polling, add "Checking..." text to the right of the "Set Google Billing" button and animate the ...~~
- [x] When a billing account is detected, remove button and change to a dropdown with the newly created billing account selected.

![image](https://cloud.githubusercontent.com/assets/5578537/21996623/2ce8eaba-dbf9-11e6-84c3-4c5ffeae3f61.png)

- [x] if they click into the billing field again, it should look something like this...

![image](https://cloud.githubusercontent.com/assets/5578537/21996429/3409d0a8-dbf8-11e6-9916-5e2828184bfa.png)

- [ ] with a billing account configured, display the "Continue" button that allows them to proceed to the final step.

**Comment by ewsopp** [comment]
# User has project(s) and billing account(s).

![image](https://cloud.githubusercontent.com/assets/5578537/21996547/c6fd8788-dbf8-11e6-8011-605151904eb1.png)

- [x] If the user has project(s) and billing account(s), then we simply show all the fields preset.
- [x] The user still has the option to configure each setting as he/she desires.

![image](https://cloud.githubusercontent.com/assets/5578537/21996570/e97a5a70-dbf8-11e6-8f01-c1c77dfd3c62.png)

![image](https://cloud.githubusercontent.com/assets/5578537/21996574/effbb236-dbf8-11e6-8268-19877f0a0eb7.png)

![image](https://cloud.githubusercontent.com/assets/5578537/21996585/f6ae47a6-dbf8-11e6-97eb-93eda47a207f.png)

**Comment by ewsopp** [comment]
- [x] If the user selects and existing project and that project already has a billing account, only display that account in the billing account field without the ability to edit it.

![image](https://cloud.githubusercontent.com/assets/5578537/22377289/4abe5140-e47f-11e6-9c5c-6ffaef8e76cc.png)
